<a href="https://colab.research.google.com/github/Ksnpriya/numpy/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #Numerical Python

#array---collection of data with same datatype(homogenious)

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a=np.array([1,2,3.0,4])
a

array([1., 2., 3., 4.])

In [ ]:
a=np.array([1,2,3,4,"a"])
print(a)

['1' '2' '3' '4' 'a']


In [ ]:
#Slicing and indexing

b=np.array([1,2,3,4,5])

#print 1,2
#print 5,4
#print 4,5
#print 2,1

In [ ]:
#print 1,2
b = np.array([1,2,3,4,5]) # Re-initialize b if it was not correctly defined or overwritten
print(b[0:2])

[1 2]


In [ ]:
print(b[-1:-3:-1])
b

[5 4]


array([1, 2, 3, 4, 5])

In [ ]:
#print 4,5
b[3::]

array([4, 5])

In [ ]:
#print 2,1
b[-4::-1]

array([2, 1])

In [ ]:
#Diamension
a=np.array([0])
a.ndim

1

In [ ]:
#if diamension is 1 then its a vector

In [ ]:
a=np.array([0,1,2,3])
a.ndim

1

In [ ]:
b=np.array([[1,2],[3,4]])
b.ndim


2

In [ ]:
print(b)

[[1 2]
 [3 4]]


In [ ]:
b.shape



(2, 2)

In [ ]:
#create a 2X2 matrix 2,3,4,5

a=np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [ ]:
print(a.shape)

(2, 2)


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.size)

4


In [ ]:
#create a 2x3 matrix and print size,shape,diamension
a=np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(a.size)

6


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
print(a.ndim)

2


In [ ]:
#create a 4X2 matrix display its size,shape and diamnsion
z=np.array([[1,2],[3,4],[5,6],[7,8]])
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(z.shape)

(4, 2)


In [ ]:
print(z.size)

8


In [ ]:
print(z.ndim)

2


In [ ]:
#create a 4x4 matrix
import numpy as np
z=np.array([[1,2,3,4],[5,3,2,2],[7,6,5,3],[3,4,3,2]])
print(z)


[[1 2 3 4]
 [5 3 2 2]
 [7 6 5 3]
 [3 4 3 2]]


19.09.2025


In [ ]:
#idexing
z[0]

array([1, 2, 3, 4])

In [ ]:
z[:,0] #column only

array([1, 5, 7, 3])

In [ ]:
z[1,1]

np.int64(3)

In [ ]:
z[2,2]

np.int64(5)

In [ ]:
z[3,2::]

array([3, 2])

In [ ]:
z[3,2:]

array([3, 2])

In [ ]:
z[2:,2:]

array([[5, 3],
       [3, 2]])

In [ ]:
z[1,1]

np.int64(3)

In [ ]:
z[1,2]

np.int64(2)

In [ ]:
z[2:,1:3]

array([[6, 5],
       [4, 3]])

In [ ]:
z[1:3,3]

array([2, 3])

In [ ]:
z[1:3,0:3]

array([[5, 3, 2],
       [7, 6, 5]])

In [ ]:
z[1:3:,1:3]

array([[3, 2],
       [6, 5]])

In [ ]:
z[0:3,1:]

array([[2, 3, 4],
       [3, 2, 2],
       [6, 5, 3]])

In [ ]:
z[0:,1]

array([2, 3, 6, 4])

In [ ]:
z[0:,0:]

array([[1, 2, 3, 4],
       [5, 3, 2, 2],
       [7, 6, 5, 3],
       [3, 4, 3, 2]])

In [ ]:
z

array([[1, 2, 3, 4],
       [5, 3, 2, 2],
       [7, 6, 5, 3],
       [3, 4, 3, 2]])

In [ ]:
#Zero Matrix

z=np.zeros([3,3,3])
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
z=np.zeros([3,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
z=np.zeros([3,3,3],dtype=complex)
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
z=np.zeros([2,3,3],dtype=complex)
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
z=np.zeros([2,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create a 2x2 matrix
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.array([[3,1],[6,7]])
b

array([[3, 1],
       [6, 7]])

In [ ]:
b.shape

(2, 2)

In [ ]:
a.shape

(2, 2)

In [ ]:
#Matrix operations
#1.Addition
print(a+b)

[[ 4  3]
 [ 9 11]]


In [ ]:
#2.Substraction
print(a-b)

[[-2  1]
 [-3 -3]]


In [ ]:
#3.Multiplication
print(a@b)

[[15 15]
 [33 31]]


In [ ]:
#a*b is not a matrix multiplication

In [ ]:
#4.Division
print(a/b)

[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
#Full Matrix
#All elements are same
z=np.full([3,3],5,dtype=int)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#create a 3X4 matrix with value 9 and datatype complex
z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#Identity Matrix
#Squre matrix with diagonal elements ones(from left top to right bottom)
z=np.identity(3,dtype=int)
z

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#create a 4x4 matrix
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
y.size #find total no.of elements

16

In [ ]:
y.ndim

2

In [ ]:
#to change the shape then no of elments should be remains same
a=y.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
b=y.reshape(16,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [ ]:
#arange ............to get array of particular number

a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange
b=np.arange(1,11).reshape(5,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix with float values
a=np.array([[2.5,3.6,3.5],[1.5,1.4,6.5],[7.1,2.5,7.1]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.4, 6.5],
       [7.1, 2.5, 7.1]])

In [ ]:
#floor
z=np.floor(a)
z

array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 2., 7.]])

In [ ]:
#ceil
z=np.ceil(a)
z

array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 3., 8.]])

In [ ]:
#round
z=np.round(a) #will round to if .5 comes it will round to nearest even number
z

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [ ]:
#create a 3x3 matrix
import numpy as np

a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.max()


np.int64(9)

In [ ]:
a.max(axis=1) #max element in each row

array([3, 6, 9])

In [ ]:
a.max(axis=0) #max element in each column


array([7, 8, 9])

In [ ]:
a.min()

np.int64(1)

In [ ]:
a.min(axis=1)

array([1, 4, 7])

In [ ]:
a.min(axis=0)

array([1, 2, 3])

22.09.2025

In [ ]:
#to find total sum
a.sum()

np.int64(45)

In [ ]:
a.sum(axis=1)#row

array([ 6, 15, 24])

In [ ]:
a.sum(axis=0)#column

array([12, 15, 18])

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [ ]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [ ]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [ ]:
#flatten
a.flatten() #any matrix converts to 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#sorting
#create a 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])
a

array([[3, 4, 1],
       [5, 3, 1],
       [6, 9, 8]])

In [ ]:
a.ndim

2

In [ ]:
#sort
b=np.sort(a,axis=0)
b

array([[3, 3, 1],
       [5, 4, 1],
       [6, 9, 8]])

In [ ]:
b=np.sort(a,axis=1)
b

array([[1, 3, 4],
       [1, 3, 5],
       [6, 8, 9]])

In [ ]:
#argsort on the basis of indexing
c=np.argsort(a,axis=1)
print(c)

[[2 0 1]
 [2 1 0]
 [0 2 1]]
