<a href="https://colab.research.google.com/github/Ksnpriya/numpy/blob/main/DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np   # numerical python

#array collection of data with same datatype(Homogenious)

a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a=np.array([1,2,3.0,4])
a

array([1., 2., 3., 4.])

In [ ]:
a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing :forward slicing,backward slicing

b=np.array([1,2,3,4,5])

#print 1,2
#print 5,4
#print 4,5
#print 2,1
print(b[0:2])
print(b[-1:-3:-1])
b[3:5]



[1 2]
[5 4]


array([], dtype=int64)

In [ ]:
#diamension
a=np.array([0,1,2,3,4,5])
b=np.array([[1,2],[3,4]])
a.ndim #diamension=1 vector
b.ndim #diamension=2 matrix
print(b)
b.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3
#4,5
z=np.array([[2,3],[4,5]])
print(z)
print(z.shape)
print(z.ndim)
print(z.size)

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print,size,shape,diamension
w=np.array([[1,2,3],[4,5,6]])
print(w)
print(w.size)
print(w.ndim)


[[1 2 3]
 [4 5 6]]
6
2


In [ ]:
#create a 4x2 matrix display size ,shape,diamension

a=np.array([[1,2],[3,4],[5,6],[7,8]])


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
(4, 2)
2


In [ ]:
#create a 4x4 matrix #matrix diamension will be 2
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b)
print(b.size)
print(b.shape)
print(b.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16
(4, 4)
2


In [ ]:


b[:,0] #to get first column

array([ 1,  5,  9, 13])

In [ ]:
b[0] #to get first row

array([1, 2, 3, 4])

In [ ]:
b[1,1]

np.int64(6)

In [ ]:
b[2,2] #to get 11 from the matrix

np.int64(11)

In [ ]:
#to get[15,16]
b[3,2:]

array([15, 16])

In [ ]:
b[2:,2:]

array([[11, 12],
       [15, 16]])

In [ ]:
b[2:,1:3]

array([[10, 11],
       [14, 15]])

In [ ]:
b[1:3:,3]

array([ 8, 12])

In [ ]:
b[1:3,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
b[1:,0:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
b[0:,1]

array([ 2,  6, 10, 14])

In [ ]:
b[0:,0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#zero matrix

z=np.zeros([3,3,3],dtype=complex) #float,int
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
z=np.zeros([2,3,3],dtype=complex)
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create 2x2 matrix
a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)


[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition
print(a+b)
#matrix substraction
print(a-b)
#matrix multiplication
#print(a*b)#is not multiplication
print(a@b) #multiplication
print(a.dot(b)) #multiplication
#matrix division
print(a/b)
#magic__add__


[[ 4  3]
 [ 9 11]]
[[-2  1]
 [-3 -3]]
[[15 15]
 [33 31]]
[[15 15]
 [33 31]]
[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
#full matrix
z=np.full([3,3],5,dtype=int)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#create 3x4 matrix with value 9 and data type complex
b=np.full([3,4],9,dtype=complex)
b

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix
c=np.identity(3,dtype=int)
c


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
c=np.identity(3)
c


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c=np.eye(3) #identity
c


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a 4x4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)
print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=y.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
#arange

a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix with float values
a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.1, 2.5, 7.1]])

In [ ]:
#mathematical operations
#floor
z=np.floor(a)
z

array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 2., 7.]])

In [ ]:
#ceil
z=np.ceil(a)
z

array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 3., 8.]])

In [ ]:
#round
z=np.round(a)
z
#.5 round towards even number

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [8]:
#create a 3x3 matrix
import numpy as np

a=np.arange(1,10).reshape(3,3)

print(a)

a.max()
a.max(axis=1)#each row max element
#numpy axis=1 row,axis=0 column
a.max(axis=0)
a.min()
a.min(axis=1)
a.min(axis=0)
a.sum()
a.sum(axis=1)
a.sum(axis=0)
np.sqrt(a)
np.sin(a)
np.cos(a)
np.tan(a)
a.flatten() #to convert any matrix into one diamension

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#sort
#create 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print (a)
b=np.sort(a,axis=0)
print(b)
c=np.argsort(a,axis=1)
print(c)

[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[3 3 1]
 [5 4 1]
 [6 9 8]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]


In [ ]:
#array
#size,shape,ndim,slicing
#Zeros,ones,identity,dull
#addition,sub,multiplication
#arange,reshape
#sum,min,max
#sort,argsort
#flatten